version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: devbook-db
    environment:
      MYSQL_ROOT_PASSWORD: devbook
      MYSQL_DATABASE: devbook
      MYSQL_USER: devbook
      MYSQL_PASSWORD: devbook
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
